[package]
name = "wasm-instrument"
version = "0.1.1"
edition = "2021"
rust-version = "1.56.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT OR Apache-2.0"
description = "Instrument and transform wasm modules."
keywords = ["wasm", "webassembly", "blockchain", "gas-metering", "parity"]
categories = ["wasm", "no-std"]
repository = "https://github.com/paritytech/wasm-instrument"
include = ["src/**/*", "LICENSE-*", "README.md"]

[dependencies]
parity-wasm = { version = "0.42", default-features = false }

[dev-dependencies]
binaryen = "0.12"
diff = "0.1"
rand = "0.8"
wabt = "0.10"

[features]
default = ["std"]
std = ["parity-wasm/std"]
atomics = ["parity-wasm/atomics"]
bulk = ["parity-wasm/bulk"]
multi_value = ["parity-wasm/multi_value"]
sign_ext = ["parity-wasm/sign_ext"]
simd = ["parity-wasm/simd"]
